### ISSUE TITLE
GHG emissions and how the earth temperature and precipitations have changed and will change (focus on global economies)

### ISSUE THREAD

**Issue by Jorge-Solana** [Ironhack-Data-Madrid-Agosto-2021/W3-pipelines-project#2]
https://github.com/Jorge-Solana/GHG-emissions-and-temperature-on-Earth

**Comment by AnaAGG** [comment]
# Proyecto pipelines

Hola hola Jorge 🙋🏻‍♀️ vamos con el segundo proyecto! 

## README

Suuper readme Jorge, enhorabuena! 

- Si pones porque has seleccionado los 6 paises con los que trabajas ya te queda 🔝🔝


- Para que la metodología no se haga tan "dura" de leer lo que puedes hacer es ponerlo más en formato de *bullet points* y sean frases cortas 😉
## Estructura del repo

Suuper bien la estructura Jorge, solo te dejo por aquí un par de detalles para que te quede todo perfectito: 

- Una que se llame por ejemplo `data` donde guardes todos los `.csv` de tu repo

- Otra carpeta que se llame por ejemplo `Notebooks` donde guardemos los jupyters. Si ya a estos ficheros les ponemos un número para saber el orden de trabajo del proyecto. 

## Sintáxis de código

Vamos con el código, antes de nada... plisss 🙏 los prints infinitos en la respuesta de la API. Te voy desgranando documento a documento: 

- **cleaning_functions** 
  
  - Los docstrings ya lo hablamos hoy como hacerlo más claros. De todas formas te dejo por [aquí](https://www.google.com/search?q=docstrings+python&rlz=1C5CHFA_enES951ES951&oq=docstring&aqs=chrome.0.69i59j69i57j69i59j0i512l4j69i61.3312j0j7&sourceid=chrome&ie=UTF-8) algo de documentación sobre como hacer un buen *docstring*
  
  - En la función `limpio`, solo como detalle, yo dropearía todas las columnas que quiero quitar en una única linea de código. Al final te quedaría algo como esto: 

    ```python
    def limpio(df):
      df.reset_index(inplace=True)
      df['Country'] = 'USA', 'Germany', 'China', 'UK', 'India', 'Rusia'
      df.drop(['Interval_Years', "index"], axis = 1, inplace=True)
      
      return df
    ```
  - EL archivo esta perfectito, pero si te fijas tienes el mismo código que se repite todo el rato pero para distintas urls. Posible solución, crearnos una función que lo haga todo y luego crearnos una lista con las urls. Te dejo por aquí un poco de pseudocódigo para que te hagas una idea:

    ```python

    def full_data(url):

    # la url se la pasaremos en formato string. 
      paises_ISO3 = ['USA', 'DEU', 'CHN', 'GBR', 'IND', 'RUS']

      finalito =[]
      for i in paises_ISO3:
          url = ulr + f{"i"}
          df = cl.api(url,'1980 1999')
          finalito.append(df)

      old_temp = pd.concat(finalito)
      old_temp = cl.limpio(old_temp)
      return old_temp
    ```
  - **Visuals**
    - Cuando seleccionas solo algunas columnas sobre el dataset de `gas_emission` has puesto una buena lista de columnas, pero todas ellas son las primeras del dataframe. Como curiosidad, en pandas también podemos hacer esto sin especificar el número de columnas. ¿Cómo? 

      ```python
      df.iloc[:, 0:2]

      # los primeros dos puntos hacen referencia a las filas, por lo tanto nos indican que queremos todas las filas
      # la segunda parte después de la coma, indica las columnas, yo le estoy diciendo en el ejemplo que me devuelva las dos primeras columnas. 
      ```
    - Tienes un proceso de limpiado guapo en este jupyter, crea funciones y al `.py` 

    - En al gráfica molona que tienes con 4 *subplots* como reto, hacerlo todo con un for para evitar repetir tantas lineas de código. Si no te sale dime y lo miramos 😉
  
    Por el resto todo perfectito Jorge, suuper buen trabajoooo 💪
## TODOs

Casi todo lo que te comenté con detalles para atomizat código y hacer que el flujo de trabajo sea mejor. Te dejo por aquí una lista/resumen con las principales cositas: 

- Meter alguna carpeta más en nuestro proyecto para que quede perfectamente organizado
- Modularizar un poco más algunas parte del código 
- Los *docstrings* para que queden perfectitos

Aún con todo , hiciste muy buen proyecto Jorge!! Increible la evolución de tu código en estas semanas 😉. Te has peleando con una API, has hecho limpieza, te has creado alguna función y has hecho una buenísima visualización!! 

![image](https://user-images.githubusercontent.com/75084991/132202501-97742fb8-f56f-4e66-b0e1-416723fd6615.png)
