### ISSUE TITLE
Nuclear-power

### ISSUE THREAD

**Issue by jalex141** [Ironhack-Data-Madrid-Agosto-2021/W3-pipelines-project#3]
https://github.com/jalex141/nuclear-power.git
Alejandro

**Comment by AnaAGG** [comment]
# Proyecto pipelines 

Hola hola Alejandro 🙋🏻‍♀️ vamos con el segundo proyecto! 

## README 

El readme está bien, tiene los apartados necesarios para entender tu trabajo y poder seguirlo sin problema. Vamos con algunos detalles por si te aportan valor: 

- En varios puntos (en tus hipótesis y en las librerias) has hecho como un listado pero se ve de una forma "rarinchi" (unos a continuación de los otros). Es un detalle, pero en el readme es importante que las cosas estén bien ordenadas ya que es lo primero que ven de nuestro trabjo. Tiene que estar impoluto
- Pones las librerias, lo cual esta bien. Si ya pones los links a la documentación oficial estaría perfecto 😉

  ¿Cómo podemos poner un link a la documentación oficial?

  ```
  [pandas](https://pandas.pydata.org/docs/)
  ```
## Estructura del repo

Suuper bien 🔝, solo algunos detalles

- Si añades una carpeta de *Notebooks* donde guardes todos los jupyters, si ya los numeras para saber cual es el orden de trabajo quedaría perfectooooo 💪 


- Se te pasó un archivo temporal dentro de la carpeta `src`, el `__pycache`. Lo ideal es que lo metas en el `.gitignore`

- Dentro de la carpeta `src` tienes un archivo `ipynb`, en esta carpeta debemos tener solo archivos `.py` donde tengamos los ficheros con las funciones de apoyo que usaremos en el jupyter. 

Por el resto nada que comentar 💪

## Sintaxis de código

- **cleaning.py**
  - En general tienes los *docstrings* en las funciones, pero como otras cosas en python hay una convención para hacerlos. Que tienen que tener básicamente los *docstrings*?
    - Qué es lo que hace la función
    - Qué parámetros recibe
    - Qué nos devuelve la función

    Te dejo por [aquí](https://www.python.org/dev/peps/pep-0257/) algo de documentación basado en el PEP8 de python

- **pipeline.py**
  - Suuper bien este fichero, con funciones que has creado en el archivo *cleaning.py* devolviendo un `csv` limpio 👏🏽. 

- **scrapping** 
  - Tienes una función en este jupyter, acuerdate de llevarlas siempre al `.py` e importala desde el jupyter. Archivos `.py` podemos tener todos los que queramos, nos podemos hacer uno para la limpieza, otro para el *scrapping* etc. 
  - En este jupyter podrías crear otra función para hacer el *scrapeo*, ¿Cómo quedaría en este caso el código?

    ```python
    url = "https://www.scielo.br/j/motriz/a/xjNfHRWhzpxWMDvYjgKQKGP/?lang=en#ModalTablet2"

    def scraping(url):
      soup = BeautifulSoup((requests.get(url)).content)
      body = soup.find_all(name="div",
      class_="modal-body")

      cols = body[3].find_all("tr")
      return cols[2:]

    res_clean = scraping(url)

    # este res_clean serán los datos que entren en tu próxima función `get_stat` 
    ```
  - Después de la funcion de `get_stat` tienes un pequeño proceso de limpieza, si lo metes en una función este jupyter te quedará perfecto. 

- **visualization**
  
  Suuper trabajo en esta parte del proyecto Alejandro. Pero again vamos a por unos detalles por si te aportan valor: 

  - Cuando haces los subplot  por *discipline by weight*, explica por que tomas esos valores concretos para hacer los subsets. Al final en esta parte debe quedar todo muy claro y explicado. 
  - En esta parte *correlation to bodyweight across disciplines* 
    Si te fijas, tienes el mismo código para distintos dataframes y columnas, intenta para el futuro meter todo esto en un bucle for para evitar tener lineas de código repetidas 😉. 

    Esto lo puedes aplicar al resto de gráficas que tienes donde repites código
  - Y lo más importnate en este jupyter, no tienes nada de nada de interpretación de los resultados 😔. No solo tienes que hacer una descripción de las figuras si no explicar el porqué de los resultados que obtenemos 

## TODOs

Buen trabajo en general Alejandro, te dejo por aquí un pequeño resumen de los puntos más importantes a repasar

- Modularizar código, evitando usar código que se repita múltiples veces. 
- *Storytelling*
- Los *docstrings* suuper importantes hacerlos bien


Bueno Alejandro, segundo proyecto superado, enhorabuena! 

![image](https://user-images.githubusercontent.com/75084991/132142256-ef97a4ca-ba18-49c1-8db7-e3bb4ebd237d.png)
