### ISSUE TITLE
Are earthquakes and Volcanic eruptions related?

### ISSUE THREAD

**Issue by diegodiazgarciadev** [Ironhack-Data-Madrid-Agosto-2021/W3-pipelines-project#4]
https://github.com/diegodiazgarciadev/earthquake

**Comment by AnaAGG** [comment]
# Proyecto pipelines

Hola hola Diego 🙋🏻‍♀️ vamos con el segundo proyecto! 

## README

Super completo tu readme Diego, buen trabajo, tienes los objetivos, tu hipótesis, y algunos resultados. Te dejo por aquí algunos detalles por si te aportan valor para futuros readmes: 

- Me ha faltado algo de info sobre las APIs que has usado y que información nos daban, tanto para los volcanes como para los terremotos. 

- Cuando pones los links a la página de kaggle en *markdown* tenemos una forma de ponerlo de una forma más elegante 

    ```
    [volvanoeruptions](linkhttps://www.kaggle.com/jessemostipak/volcano-eruptions) # lo que veremos será un hiperlink con la palabra que pongamos entre los corchetes que nos llevará a la página de kaggle
    ```

- Me han faltado las librerías que has usado en este proyecto y si ya pones los links a la documetación ofical sería perfecto! 


## Estructura del repo

En general poco tengo que decirte sobre la estructura de tu repositorio, solo un cosita: 

- Te puedes crear una carpeta más que se llame por ejemplo `Notebooks` donde guardes todos los notebooks que has creado en este proyecto, si ya los numeras para saber el orden de trabajo sería estupendo 😉

## Sintaxis de código

Vamos archivo por archivo viendo algunos detalles: 

- **earthquake_cleaning.py** 

  Poco que decirte en este archivo, está suuper bien, solo por ponerme un poco quisquillosa y el `.py` te quede perfecto:

  - Puedes meterlo todo en una función que reciba como parámetro un path de donde leer un csv. En este caso, tu código podria quedar más o menos así

    ```python
      def df_earthquakes(path): 

          df = pd.read_csv(path)
    
        df_earthquakes = df[['Date', 'Time', 'Latitude', 'Longitude',
                      'Type', 'Depth', 'Magnitude']]


        df_earthquakes["Date"] = pd.to_datetime(df_earthquakes["Date"],utc=True).dt.strftime('%Y-%m-%d')
    
        try:
            df_earthquakes["Year"] = df_earthquakes["Date"].apply(cf.get_year)
        except TypeError as err:
            print("type error", err)
        

        return df_earthquakes.to_pickle("./data/df_earthquakes_cleaned")

    # esta función la guardamos en el `.py`de soporte y la llamamos desde el .py de descarga y limpieza del csv
    df_earthquaker("./data/earthquake_ds.csv")
    ```
  - Cuando haces esto

    ```python
    eruptions_df = eruptions_df[(eruptions_df["eruption_category"]!="Discredited Eruption")]
    eruptions_df = eruptions_df[(eruptions_df["eruption_category"]!="Uncertain Eruption")]

    # como lo tienes esta bien, pero recuerda que lo podemos poner en una única linea de código 
    eruptions_df = eruptions_df[(eruptions_df["eruption_category"]!="Discredited Eruption") & (eruptions_df["eruption_category"]!="Uncertain Eruption")]
    ```
- **jupyter Earthquake**
  
  - Tienes la función `call_google_api` dentro del jupyter, recuerda meterlas en un `.py` e importala en el jupyter
  - Utilizas el tipo de gráfico `scatter_geo` en varias ocasiones a las que les pasas distintos parámetros, si haces una función para este tipo de gráfico en vez de repetir el código múltiples veces quedaría perfecto el jupyter 💪


-  **jupyter Volcano**
   -  Ya te lo comentamos en la presentación de tu proyecto, pero te lo dejo por escrito también. En las gráficas que comparas el número de volcanes y el número de erupciones lo ideal es que lo hicieras en una única gráfica. 
   -  Lo mismo que el jupyter anterior, crear una función que puede ser la misma que la anterior para hacer los mapas.
   -  De nuevo, las funciones al `.py` que nuestro jupyter quede lo más limpio posible 😉
   -  En general es increíble el trabajo que has hecho en este jupyter, solo como detalle me ha faltado un poco más de *storytelling*, nos pones muchos mapas pero nos falta la interpretación, el por qué! 


## TODOs
 
 Te dejo por aquí un resumen de los principales comentarios que te hice en este proyecto: 

 - Modularizar el código en algunos jupyters llevandonos las funciones al `.py`
 - Crearnos alguna función para los mapas
 - Cambiar algunos detalles en el readme (los links) o en la estructura del proyecto (como crear alguna carpeta más)


Aún con todo, suuuper buen trabajo Diego, has creado un proyecto buenísimo! Seguimosss 💪🔥

![image](https://user-images.githubusercontent.com/75084991/132315471-8136b730-82f3-4d85-977b-27d257b17e84.png)
