### ISSUE TITLE
CO2 and Temperatures Seasonality

### ISSUE THREAD

**Issue by JulianTrufero** [Ironhack-Data-Madrid-Agosto-2021/W3-pipelines-project#5]

**Comment by JulianTrufero** [comment]
https://github.com/JulianTrufero/CO2-and-Temperatures-Seasonality

**Comment by AnaAGG** [comment]
# Proyecto pipelines

Hola hola Julián 🙋🏻‍♀️ vamos con el segundo proyecto! 

## README
Vamos con el readme que aunque corto es bastante completo Julián 😉💪. 
- Cosas que le aportan mucho valor a tu readme
  - Que hayas indicado la estructura de las carpetas y de archivos que tienes en el repo
  - Que hayas añadido los links del dataset y de la API
  - Que hayas indicado las librerias que usas
  - Cual es el objetivo del proyecto, y como lo hiciste
- Cositas que podemos añadir para aportarle más valor a nuestro readme
  - Dividir el readme en subapartados. Por ejemplo:
    - Introducción y objetivo del proyecto: por qué has elegido este tema, pon un poco en contexto al lector de cual es el problema. Tu objetivo final del proyecto (en una frase)
    - Datos que has usado: esto lo tienes perfecto en tu readme, con los links a la documentación y la página para que se los descargen
    - Workflow: explicando en *bullet points* los pasos que se has seguido en el proyecto para alcanzar tu objetivo. Esto también lo tienes, pero tal vez lo puedes ampliar un poco más, pero no mucho. 
    - Resultados: completamente optativo
    - Librerias: una lista de las librerias que usamos con sus links (esto ya lo tienes también)

Parece que son muchas cosas pero no! Son simplemente detalles 😉🤓. 

## Estructura del repo

Suuuper bien organizado el repo Julian 👏🏽. Pero como siempre algún detallito hay, vamos con ellos: 

- En la carpeta `src` tienes un fichero que se llama `functions`. Recuerda, evitamos usar esos nombres tan generales y les damos un nombre algo más autoexplicativo , por ejemplo `cleaning_functions`
- Puedes crear una carpeta que se llame `data` donde guardes los datos que has usado para hacer el proyecto:
  - El csv que te descargas de kaggle o el dataset limpio
  - El resultado de la llamada a la API limpito guardado en un `csv`. Además, hacer esto nos evitara posibles problemas que podamos tener en caso de que la API cambie, no funcione en determinado momento. Básicamente "protegernos" de quedarnos sin los datos. 
- ¿Con los jupyters que podemos hacer? Podemos crear una carpeta que se llame por ejemplo `Notebooks` donde metamos los jupyters. Y si encima los numeramos para saber el orden de trabajo quedaría 🔝🔝

## Sintaxis de código
- Suuper bien documentado el archivo ejecutable `.py`, enhorabuena por ese trabajo 🎉

Vamos desgranando cada uno de tus archivos: 

- **ejecutable cleaning**
  - El `.py` esta suuuper bien, pero como detalle, a lo largo del archivo repites llamadas a las funciones de forma repetitiva, intenta atommizarlo y que no se repita, haciendo un for loop y aplicando la función a la misma vez para distintos datos!!


  - Super buen trabajo metiendo en este archivo tanto la limpieza de los datos del `csv` como la llamada a la API 🔝
  - ⚠️ Ojo que te has dejado el token de la RAPIDAPOI a la vista en este ficherooooo 😱
  - Venga en la función `get_carbon_data` podemos atomizar un poco el código y hacer nuestra función un poquito más cortita y aún así entendible

    ```python
    def get_carbon_data(url):
        url = f"{url}"
        headers = {
        'x-rapidapi-host': "daily-atmosphere-carbon-dioxide-concentration.p.rapidapi.com",
        'x-rapidapi-key': "XXXXXX" # 🔴⚠️  TU TOKEN ESTABA AQUÍ
        }
        response = requests.request("GET", url, headers=headers).json() # hago la request y creo el json a la vez
    
    return pd.DataFrame(response['co2']) # y el dataframe lo llevo directamente al return 
    ```
- **visualizations**
  - Vamos con el plot *TEMPERATURAS MENSUALES (2012 - 2017)* 

    En este plot tienes 5 lineas de código que soy iguales solo que cambiando lo que ploteas en el eje y. Como reto para el futuro, intenta hacerlo en un for loop. 

    Podrías crearte una lista con lo que quieres plotear en el eje y y un range para cambiar lel `ax` de tu plot. 


  - Por último, en casi todas las gráficas tienes la descripción y una posible explicación, pero no en todas. Intenta hacerlo en todos 😉


## TODOs

- Atomizar un poco el código para no repetir mucho nuestro código
- Darle una vueltina al readme y a la estructura del repo con los detallines que te dije


Suuuper trabajazo en este proyecto Julián!! Enhorabuena, en este proyecto hemos aprendido a nutrir los datos originales usando una API y extraer conclusiones de ellos 💪🔥


![image](https://user-images.githubusercontent.com/75084991/132132142-8302b913-d79c-4777-b564-10621debb533.png)
