### ISSUE TITLE
Air Pollution and Population

### ISSUE THREAD

**Issue by DiegoCefalo** [Ironhack-Data-Madrid-Agosto-2021/W3-pipelines-project#7]
https://github.com/DiegoCefalo/AirPollutionAndPopulation

**Comment by AnaAGG** [comment]
# Proyecto pipelines

Hola hola Diego 🙋🏻‍♀️ vamos con el segundo proyecto! 

## README

En realación al readme, super que hayas puesto cual es la base de datos, como añades valor a tu dataset con *scraping*, que pongas algunos resultados y que al final pongas las librerias que has usado y sus links a la documentación oficial. 

Vamos con algunos detalles que me han faltado: 

- Contar un poco que has hecho con los datos. Dices que la limpieza ha sido "mínima", pero cuenta un poco el *workflow*

- De toda los datos que hay en el dataset y en los datos que has *scrapeado* cuales son los que has usado tu para tu proyecto?

- Porque has decido hacer este proyecto? La motivación de correlacionar estos dos sets de datos

Como te digo son detalles que harán que tu readme vaya incrementando su valor 💪

## Estructura del repo

La estructura del repo esta perfecta, ningún archivo temporal fuera del `.gitignore`  y las carpetas claramente diferenciadas 🔝. 

Solo como detalle para el futuro: 
- Hubiera estado bien que crearas una carpeta (que se podría llamar "data") donde metieras el csv del dataset de *kaggle* e incluso los datos resultados del *scrappping* limpitos para tenerlos en un `.csv`. 
- ¿Por qué puede ser importante tener los datos, sobre todo los del *scrapping* en un `.csv`. Imagina que por lo que sea el *scrapping* empieza a no funcionar porque la página cambia, o deja de funcionar temporalmente. En ese caso podremos seguir trabajando a partir del `.csv` 
- Una cosa interesante que puedes hacer también es numerar los jupyters para saber cual es el orden que debemos seguir para poder entender tu proyecto a la perfección. 

- Tienes algunas cosas en inglés y otras en español (en general en español), intenta unificarlo para el futuro.

Por el resto, buen trabajo, son solo detalles Diego! 

## Sintaxis de código

- Si bien la limpieza de tu dataset y de los datos scrapeados es pequeña lo ideal es que crearas un archivo `main.py` que funcionara como ejecutable. 

    Respecto a esto, en realidad solo te faltó crear ese archivo `main.py` donde llamaras a la función `get_info`. Este archivo te quedaría algo más o menos como esto

    ```python
    import las librerias que necesites
    import src.airpo_resources as ar

    # llamamos a tu función

    data = get_info()
    data.to_csv("scraping_data.csv")

    # luego nos iremos a la terminal, haremos:

    python3 main.py 
    # y después de esto se ejecutará tu código y se creará el csv en tu carpeta. 
    ```
- Poco más tengo que decirte ya que en este proyecto tienes poca parte de código
- Suuuper 🔝 el jupyter contando la historia
  
## TODOs

- En el readme añade esos detallines que te comenté y te quedará perfecto

- Me ha faltado el ejecutable, ese fichero `.py` al que le vas a pasar una *url* que *scrapear* y te devuelve un dataframe ya limpio


Bueno Diego, aunque no ha sido tu mejor obra ya que podrías haber exprimido algo más los datos has hecho un buen proyecto. 

![image](https://user-images.githubusercontent.com/75084991/131810326-61e405ba-7e33-467e-8c3d-2fba2f54f8e9.png)
