### ISSUE TITLE
Ascensos-Everest-Jaime-Cabanyes

### ISSUE THREAD

**Issue by jaimecabanyes** [Ironhack-Data-Madrid-Agosto-2021/W3-pipelines-project#8]
https://github.com/jaimecabanyes/-Ascensos-Everest-Jaime-Cabanyes

**Comment by AnaAGG** [comment]
# Proyecto pipelines

Hola hola Jaime 🙋🏻‍♀️ vamos con el segundo proyecto! 

## README
En lineas generales el readme esta bien, pero ya sabes que siempre saco algún detallin. Vamos allá con algunos detalles del readme: 

- Para el futuro y como reto te animo a que trastees con los distintos formatos de markdown para hacer que quede más estructurado y fácil de leer (con apartados, subapartado, etc. )

  Te dejo por [aquí](https://www.markdownguide.org/cheat-sheet/) algo de documentación para que te vayas familiarizando con markdown! 

- De donde has sacado el dataset sobre los aplinistas que han alcanzado el Everest? Indícalo, pon el link a la página donde nos podemos descargar los datos originales. 
- Cuenta que haces *web scraping* para nutrir de más datos a los datos originales descargados en el `.csv`, por que lo haces y de que página lo haces. 
- Indicas las librerías que has usado en este proyecto. Sobre esto dos detalles: 
  - No hace falta que pongas `import pandas as pd `, con que pongas `pandas` es suficiente
  - Si pones los links a la documentación oficial te queda perfecto 😉.¿Cómo podemos meter un link en markdown?
      ```
      [pandas](https://pandas.pydata.org/docs/)
      # esto nos creara un hipervínculo que nos llevará a la página de la documentación oficial
      ```

## Estructura del repo

Suuuper bien la estructura del repo Jaime! No se te ha pasado ningún archivo temporal y esta todo bastante bien organizado 🔝. Te dejo por aquí un par de detalles por si te aportan valor: 

- Tienes una carpeta de `data` lo cual esta perfectisimo, peeero se te quedó el archivo `Mt_Everest_Ascent_Data.csv` fuera de esa carpeta. 

- Para que te quede redondito del todo puedes crearte una carpeta nueva donde vayas guardando todos tus jupyters. Si encima, numeras los jupyters para saber el orden de trabajo te quedaría perfect! 

- Recuerda los *docstrings* en las funciones!! Te dejo por [aquí](https://www.python.org/dev/peps/pep-0257/) con algo de documentación sobre como hacer unos buenos *docstrings*
- Tienes algunas cosas en ingles y otras en español. Intenta homogeneizarlo y ponerlo todo en un idioma. Yo personalmente, si te sientes cómodo lo haría es ingles. 
- Tienes tres `csv` que se llaman `table1`, `table2` y `table3`. Ponles nombres que sean algo más descriptivos, que sepamos de una forma más sencilla que contiene ese dataset
  
## Sintáxis de código

Vamos fichero por fichero para que este un poco más organizado: 

- **ejecutable main**

  Gran trabajo en este fichero, te has creado muchas funciones con objetivos específicos que luego llamas a todas en otra gran función 🔝. 
  Tu set de datos tenía poco que limpiar, por lo tanto poco tengo que decirte aquí. Solo como detalle, 
  - lo ideal en el `.py` es que nos guarde el dataset limpio. Para esto, lo único que tendrías que haber hecho es añadir una linea nueva exportando el csv 

    ```python
    final.to_csv("data_clean.csv")
    # con esto se nos creará el fichero limpio en nuestra carpeta cuando ejecutemos el `.py`
    ```
  - Aquí tienes librerías importadas que en realidad no usas, como las de visualización. Pon unicamente aquellas librerías que uses en ese fichero. 


- **jupyter DataFrame cleaning**

  Este jupyter supongo que era en el que tu hiciste todas las pruebas para el `.py`. Como recomendación te diria que lo metieras en el `.gitignore` para que la gente que ve tu repo no vea ese archivo ya que todo ese código esta en el `.py` de funciones y en el `main.py`. Al fin y al cabo esta es una de las principales utilidades del `.gitignore`

- **jupyter WEB Scraping**

  - Las funciones a un `.py`. De este tipo de archivos podemos tener todos los que queramos. Por lo tanto, nos podemos crear uno para la limpieza (como ya tienes) otro para las funciones que uses en el *web scrapping* etc. 
  - Este jupyter esta perfect, pero si te fijas repites el mismo código multiples veces, una para cada tabla que tienes. Por lo tanto esto es señal de... Hay que hacer funciones más universales. Vamos con tu código

  ```python
  # estas primeras lineas de código son constantes para todas las tablas, por lo  tanto las podemos meter dentro de la función
  table1 = a[0]

  tbody1 = table1.find("tbody")

  trs1 = tbody1.find_all("tr")
  # vamos allá
  def funcion_universal(row, col1, col2):

    table1 = a[0]

    tbody1 = table1.find("tbody")

    trs1 = tbody1.find_all("tr")

    # la siguiente parte también es universal para todas las tablas, por lo tanto lo mantenemos dentro de la función

    info = dict()
    
    cols3 = row.find_all("td")
    
    # por último, creas un dataframe con nombres de columnas diferentes, lo que podemos hacer aquí para que la función sea universal es pasar el nombre de las columnas como parámetros

    info[col1] = (cols3[0].text.strip())
    info[col2] = int(cols3[1].text)

    return info

    # 🔴 si te queda alguna duda sobre esta función dimelo y lo vemosss
  ```
- **jupyter Visualización**

Enhorabuena por el trabajo de visualización Jaime!!! Increible la cantidad de gráficos que has sacado y lo bien que están elegidos los gráficos. Peeero ya sabes que siempre tengo alguna cosita que decir 🤓

¿Qué me ha faltado? 

  - Que metas el *storytelling*. Haz una pequeña descripción de cada gráfica, que es lo que nos esta contando y cual es tu conclusión. 

## TODOs

Bueno, te dejo por aquí un pequeño resumen de las correcciones que te hice por si te aporta valor: 

- Funciones al `.py`
- El readme darle una vueltina y formatearlo un poco usando markdown
- *Storytelling*

Bueno Jaime, menuda evolución del primer al segundo proyecto, solo puedo darte la enhorabuena 💪. Sigue haciendolo así!!!!

![image](https://user-images.githubusercontent.com/75084991/132322805-adc32703-403f-4a42-8708-dcbbb5a75ce3.png)
